
name: Task Manager Backend CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - run : echo "Action Started.."
    - name: Checkout
    - uses: actions/checkout@v4
    - name: Run a one-line script
      run: echo "Hello world!"
    - name: Run a multi-line script
      run: |
          echo Add other actions to build, test, and deploy your project.
    - name: List files
      run: ls ${{ github.workspace }}
    - name: Print Node context
      env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Actions Completed
      run: echo "Action Completed.."